/** 应用侧再导出；契约真相源见 types.gen.ts（未来由 openapi-typescript 覆盖） */
export type {
  ApiErrorBody,
  ApiListSuccess,
  ApiSuccess,
  CreateGameRequest,
  CreateGameResponse,
  GameDetail,
  GameSummary,
  GameVersion,
  HitlResolveRequest,
  HitlResolveResponse,
  HitlWaitPayload,
  LlmConfig,
  LlmConfigCreateRequest,
  LlmConfigPatchRequest,
  LlmConfigTestResponse,
  LoginResponse,
  PublishSubmitResponse,
  RegisterResponse,
  RunDetail,
  RunSummary,
  UsageBucket,
  UsageSummary,
  User,
  WsEnvelope,
} from './types.gen'
