"""Forge 可靠性子系统（P0）：错误分类、暂停原因、节点策略、幂等。"""

from app.forge.reliability.errors import (
    DataCorruption,
    FatalError,
    ForgeRuntimeError,
    InvalidModelOutput,
    InvariantViolation,
    Provider5xx,
    ProviderRateLimit,
    ProviderTimeout,
    RecoverableError,
    SandboxOOM,
    SandboxTimeout,
    SecurityViolation,
    UserActionRequired,
    WorkerInterrupted,
    classify_exception,
    is_fatal,
    is_recoverable,
)
from app.forge.reliability.pause import (
    RecoveryInfo,
    apply_paused_metadata,
    build_pause_checkpoint,
    pause_reason_from_state,
    recovery_from_state,
)

__all__ = [
    "DataCorruption",
    "FatalError",
    "ForgeRuntimeError",
    "InvalidModelOutput",
    "InvariantViolation",
    "Provider5xx",
    "ProviderRateLimit",
    "ProviderTimeout",
    "RecoverableError",
    "RecoveryInfo",
    "SandboxOOM",
    "SandboxTimeout",
    "SecurityViolation",
    "UserActionRequired",
    "WorkerInterrupted",
    "apply_paused_metadata",
    "build_pause_checkpoint",
    "classify_exception",
    "is_fatal",
    "is_recoverable",
    "pause_reason_from_state",
    "recovery_from_state",
]
